### ISSUE TITLE
[Fix]: Navbar/footer missing from singularity.storage homepage; broken links in navbar in other instance

### ISSUE THREAD

**Issue by juliaxbow** [data-preservation-programs/singularity-website#65]
**Description**
- The navbar and footer are missing from the singularity.storage homepage. It was there as recently as last week (Nov 21) when I was last on the site. I don't believe this was an intentional change as both are still visible at /signup

- Where instances of the navbar do exist (see /signup), links to "Features", "How it Works", and "Roadmap" are broken

**Reproduce**
1. Go to singularity.storage
1a. Observe missing navbar and footer on homepage
2.  Click on "Sign up" CTA
2a. Observe navbar and footer at /signup
3. Click on "Features" "How it works" and "Roadmap" nav links
3a. Observe lack of response

**Comment by orvn** [comment]
Woah, that's not right at all. Thanks for reporting @juliaxbow, fixing asap, assigned to @tikagan.
