### ISSUE TITLE
Second signup button hangs with progress bar

### ISSUE THREAD

**Issue by dannyob** [data-preservation-programs/singularity-website#77]
![image](https://github.com/data-preservation-programs/singularity-website/assets/227660/2b6031d9-95d9-4ac0-bc57-78ddc621b74e)

The only error I get in the javascript console is the somewhat unhelpful , but the problem reproduces on https://www.browserling.com/ if it works on your end.

```
entry.DpgzhgW9.js:13 TypeError: n.set is not a function
    at D (index.Cao3vK3y.js:5:10991)
Jf @ entry.DpgzhgW9.js:13
````

I couldn't build the website locally without some apikeys and a local https key and cert (the instructions don't explain how to create or comment these out).

**Comment by orvn** [comment]
@tikagan assinging to you
